### ISSUE TITLE
Consolidate Vanilla NN Code

### ISSUE THREAD

**Issue by aashish-khub** [aashish-khub/NearestNeighbors#2]
### Tasks
- [ ] Paper read: [Vanilla NN (arXiv:2202.06891)](https://arxiv.org/pdf/2202.06891)
- [ ] Add original code from https://github.com/calebchin/DistributionalNearestNeighbors/blob/main/src/scalar_nn.py to https://github.com/aashish-khub/NearestNeighbors/blob/main/src/vanilla_nn.py
- [ ] Code reviewed  
- [ ] Code consolidated into the repository  

### Notes
Placeholder for future notes.
