### ISSUE TITLE
Consolidate TS (Two-Sided NN) Code

### ISSUE THREAD

**Issue by aashish-khub** [aashish-khub/NearestNeighbors#3]
### Tasks
- [ ] Paper read: [TS (arXiv:2411.12965)](https://arxiv.org/pdf/2411.12965)
- [ ] Original unconsolidated code added to this repo  
- [ ] Code reviewed  
- [ ] Code consolidated into the repository  

### Notes
Placeholder for future notes.
