### ISSUE TITLE
Consolidate DR (Doubly Robust NN) Code

### ISSUE THREAD

**Issue by aashish-khub** [aashish-khub/NearestNeighbors#4]
### Tasks
- [ ] Paper read: [DR (arXiv:2211.14297)](https://arxiv.org/pdf/2211.14297)
- [ ] Original unconsolidated code added to this repo: https://github.com/calebchin/DRNN
- [ ] Code reviewed  
- [ ] Code consolidated into the repository  

### Notes
Placeholder for future notes.

**Comment by albertgong1** [comment]
Abstract method:
1. Distances
2. Estimate (what to average over, how to average over them) -> Let subclass decide what auxiliary functions are needed

Dists:
- Type should be np.ndarray (vector for entry-entry case and 2D-array for full matrix case)
- Keep track of `row_dists` and `col_dists`
