### ISSUE TITLE
Consolidate DNN (Distributional NN, Wasserstein) Code

### ISSUE THREAD

**Issue by aashish-khub** [aashish-khub/NearestNeighbors#5]
### Tasks
- [x] Paper read: [DNN (Wasserstein, arXiv:2410.13112)](https://arxiv.org/pdf/2410.13112)
- [ ] Original unconsolidated code added to this repo  
- [ ] Code reviewed  
- [ ] Code consolidated into the repository  

### Notes
Placeholder for future notes.
