### ISSUE TITLE
Consolidate Syn-NN Code

### ISSUE THREAD

**Issue by aashish-khub** [aashish-khub/NearestNeighbors#7]
### Tasks
- [ ] Paper read: [Syn-NN (arXiv:2109.15154)](https://arxiv.org/pdf/2109.15154)
- [ ] Original unconsolidated code added to this repo  
- [ ] Code reviewed: [Syn-NN implementation](https://github.com/AbdullahO/What-If/blob/main/algorithms/snn_biclustering.py)  
- [ ] Code consolidated into the repository  

### Notes
Placeholder for future notes.
